---
- hosts: mywebserver
  become: yes
  task:
  - name: install java on ubantu
    apt:
     name: {{"forubantu"}}
     state: present
    when: ansible_os_family=="Debian"
  - name: install java on linux
    yum:
      name: {{"forlinux"}}
      state: present
    when: ansible_os_family="RedHat" 