---
- hosts: 172.31.37.182
  become: yes
  tasks:
  - name: install git
    apt:
     name: gat
     state: present
    tags: git
    ignore_errors: yes
  
  - name: install tree
    apt:
     name: tree
     state: present
    tags: tree

  - name: install wget
    apt:
     name: wget
     state: present
    tags: wget
      
