---
- hosts: 172.31.37.182
  become: yes
  tasks:
  - name: install git
    apt:
     name: install git 
     state: present
     tags: git
  
  - name: install tree
    apt:
     name: install tree
     state: present
     tags: tree

  - name: install wget
    apt:
     name: install wget
     state: present
     tags: wget
      
